name: mK
favicon: null
layout_spectrum: 0.8591353939846158
typography_spectrum: 0.060666057746857405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5643642041832209
  lightness: 0.5959177904296666
  saturation: 0.34409458516165614
  rhythmicContrast: 0.6440292436163872
purpose: []
